### ISSUE TITLE
OS X Yosemite 10.10.5 

### ISSUE THREAD

**Issue by MarkoH17** [wollardj/Mandrill#18]
Having problems installing mandrill via mandrillctl --install. Problem is that it install fine, but when executing mandrillctl --start, it shows an "X" next to both MongoDB and Mandrill Server. Not sure how to proceed.

**Comment by Ubertec** [comment]
Not helpful but I could never get this to work on any version of Yosemite. Mavericks 10.9.5 would give me a tick on both, then disable the server 5 seconds later and rechecking would give an "X". Basically gave up and this obviously isnt stable/updated. Sad because this looked like the best/easiest Munki Web Administration system available.
